apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus.grafana.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    component: "{{ .Values.grafana.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc | quote }}
  {{- if .Values.grafana.adminPassword }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
