apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-core
  namespace: monitoring
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      serviceAccountName: prometheus-k8s
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: monitoringnode
                operator: In
                values:
                - "true"
      containers:
      - name: prometheus
        image: prom/prometheus:v2.2.1
        args:
          - '--config.file=/etc/config/prometheus.yaml'
          - '--storage.tsdb.path=/data'
          - '--storage.tsdb.retention=48h'
          - '--web.console.libraries=/etc/prometheus/console_libraries'
          - '--web.console.templates=/etc/prometheus/consoles'
          - '--web.enable-lifecycle'
        ports:
        - name: webui
          containerPort: 9090
        resources:
          requests:
            cpu: 500m
            memory: 500M
          limits:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: prometheus-persistent-storage
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-core
      - name: prometheus-persistent-storage
        hostPath:
          path: /data/prometheus
          type: DirectoryOrCreate
