apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app: prometheus
    component: core
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
