name: prometheus
version: 1.0.0
appVersion: 2.4.3
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
sources:
  - https://github.com/prometheus/alertmanager
  - https://github.com/prometheus/prometheus
maintainers:
  - name: giantswarm
    email: info@giantswarm.io
engine: gotpl
tillerVersion: ">=2.8.0"
