apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: blackbox
  namespace: monitoring
  labels:
    app: blackbox
spec:
  type: ClusterIP
  selector:
    app: blackbox
  ports:
  - protocol: TCP
    port: 9115
    targetPort: 9115
