{
 "title": "Prometheus",
 "tags": [
  "host",
  "guest"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Rate of Samples Appended",
   "type": "graph",
   "description": "5 minute rate of samples appended",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "singlestat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{cluster_type=\"host\"})"
    }
   ]
  },
  {
   "title": "Rule Evaluation Duration",
   "type": "graph",
   "description": "Time take for rule evaluation",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{ instance }} - 0.99 quantile"
    },
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }} - 0.9 quantile"
    },
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{ instance }} - 0.5 quantile"
    }
   ]
  },
  {
   "title": "Notification Latency",
   "type": "graph",
   "description": "TIme taken to send notifications",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prometheus_notifications_latency_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{ instance }} - 0.99 quantile"
    },
    {
     "expr": "prometheus_notifications_latency_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{ instance }} - 0.9 quantile"
    },
    {
     "expr": "prometheus_notifications_latency_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{ instance }} - 0.5 quantile"
    }
   ]
  },
  {
   "title": "Memory usage/limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{container=\"prometheus\",cluster_type=\"host\"}",
     "legendFormat": "memory limit"
    },
    {
     "expr": "container_memory_usage_bytes{container_name=\"prometheus\",cluster_type=\"host\"}",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "CPU usage/limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"prometheus\",cluster_type=\"host\"}",
     "legendFormat": "cpu limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"prometheus\",cluster_type=\"host\"}[3m]))",
     "legendFormat": "cpu used"
    }
   ]
  }
 ]
}