apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: kube-state-metrics
        image: googlecontainer/kube-state-metrics:v1.2.0
        ports:
        - containerPort: 8080
