groups:
- name: deployment
  rules:
  - alert: DeploymentNotSatisfied
    expr: kube_deployment_status_replicas_unavailable{} > 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: Deployment {{ $labels.exported_namespace}}/{{ $labels.deployment }}
        is not satisfied.
