groups:
- name: pod
  rules:
  - alert: PodStuck
    expr: kube_pod_status_phase{phase="Pending"} == 1
    for: 15m
    labels:
      severity: notify
    annotations:
      description: Pod {{ $labels.exported_namespace }}/{{ $labels.pod }} is stuck in Pending.
