apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    component: "{{ .Values.grafana.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: grafana
