---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "prometheus.grafana.fullname". }}
  labels:
    app: {{ template "prometheus.name" . }}
    component: "{{ .Values.grafana.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  grafana.ini: |
{{- range $key, $value := index .Values.grafana "grafana.ini" }}
    [{{ $key }}]
    {{- range $elem, $elemVal := $value }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://{{ template "prometheus.server.fullname" . }}:{{ .Values.server.service.servicePort }}
        basicAuth: false
        withCredentials: false
        isDefault: true
        editable: false
        version: 1
      - name: Elasticsearch
        type: elasticsearch
        access: proxy
        orgId: 1
        url: http://elasticsearch:9200
        basicAuth: false
        withCredentials: false
        isDefault: false
        editable: false
        version: 1
        database: "[gslogs-]YYYY.MM.DD"
        jsonData:
          interval: Daily
          timeField: '@timestamp'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-main
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        options:
          path: /etc/grafana/provisioning/dashboards-json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-json
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "grafana-dashboards/*").AsConfig | indent 4 }}
