apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus
    component: node-exporter
spec:
  type: ClusterIP
  selector:
    app: prometheus
    component: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
