{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "$service return code",
   "type": "grafana-piechart-panel",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "traefik_requests_total{service=\"$service\"}",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Requests by service",
   "type": "grafana-piechart-panel",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service !~ \"http|https\"}[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Requests by protocol",
   "type": "grafana-piechart-panel",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(traefik_requests_total{service =~ \"http|https\"}[5m])) by (service) ",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Status code 200 over 1min",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_requests_total{service=~\"http|https\",code=\"200\"}[60s]))",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Others status code over 1min",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(increase(traefik_requests_total{service=~\"http|https\",code!=\"200\"}[60s]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Total requests over 1min",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_requests_total{service=\"$service\"}[60s]))",
     "legendFormat": "Total requests"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 7, "w": 24, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_request_duration_seconds_sum{service=\"$service\",code=\"200\"}) / sum(traefik_requests_total{service=\"$service\",code=\"200\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  }
 ]
}